export enum EModal {
  MODAL_EDIT_PRODUCT = "MODAL_EDIT_PRODUCT",
  MODAL_DELETE_PRODUCT = "MODAL_DELETE_PRODUCT",
  UNSAVE_CHANGE_PRODUCT = "UNSAVE_CHANGE_PRODUCT",
  UPLOAD_IMAGE_MODAL = "UPLOAD_IMAGE_MODAL",
}
